import { Sparkles, AlertCircle, Loader2, RefreshCw } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Collapsible } from "@/components/ui/collapsible";
import { usePostSummary } from "@/hooks/usePostSummary";

interface AiSummaryProps {
    postId: string;
}

export default function AiSummary({ postId }: AiSummaryProps) {
    const { summary, loading, error, generateSummary, retry, fromCache, initialLoading } = usePostSummary(postId);

    // While checking for existing summary, show nothing (or a subtle loader)
    if (initialLoading) {
        return null;
    }

    // If no summary exists and not loading, show the trigger button
    if (!summary && !loading && !error) {
        return (
            <div className="mt-4">
                <Button
                    onClick={generateSummary}
                    variant="outline"
                    className="gap-2"
                    size="sm"
                >
                    <Sparkles className="h-4 w-4" />
                    <span>Summarize with AI</span>
                </Button>
            </div>
        );
    }

    // Error state
    if (error) {
        return (
            <div className="mt-4">
                <Collapsible title="AI Summary" defaultOpen={true}>
                    <div className="space-y-3">
                        <div className="flex items-start gap-3 text-destructive">
                            <AlertCircle className="h-5 w-5 mt-0.5 shrink-0" />
                            <div className="flex-1">
                                <p className="text-sm font-medium">Failed to generate summary</p>
                                <p className="text-sm text-muted-foreground mt-1">{error}</p>
                            </div>
                        </div>
                        <Button
                            onClick={retry}
                            variant="outline"
                            size="sm"
                            className="gap-2"
                        >
                            <RefreshCw className="h-4 w-4" />
                            <span>Try Again</span>
                        </Button>
                    </div>
                </Collapsible>
            </div>
        );
    }

    // Loading state (no content yet) - show skeleton
    if (loading && !summary) {
        return (
            <div className="mt-4">
                <Collapsible title="AI Summary" defaultOpen={true}>
                    <div className="flex items-center gap-3 text-muted-foreground">
                        <Loader2 className="h-5 w-5 animate-spin" />
                        <div className="space-y-2 flex-1">
                            <div className="h-4 bg-muted rounded animate-pulse w-full" />
                            <div className="h-4 bg-muted rounded animate-pulse w-5/6" />
                            <div className="h-4 bg-muted rounded animate-pulse w-4/6" />
                        </div>
                    </div>
                </Collapsible>
            </div>
        );
    }

    // Summary loaded - show the summary
    if (summary) {
        return (
            <div className="mt-4">
                <Collapsible title="AI Summary" defaultOpen={true}>
                    <div className="space-y-3">
                        <div className="flex items-start gap-3">
                            <Sparkles className="h-5 w-5 mt-0.5 shrink-0 text-primary" />
                            <div className="flex-1">
                                <p className="text-sm leading-relaxed whitespace-pre-wrap">
                                    {summary}
                                </p>
                            </div>
                        </div>
                        <div className="flex items-center gap-2 pt-2 border-t">
                            <p className="text-xs text-muted-foreground flex-1">
                                Generated by AI{fromCache ? ' • Cached' : ''} • May not be fully accurate
                            </p>
                            <Button
                                onClick={retry}
                                variant="ghost"
                                size="sm"
                                className="gap-2 h-7 text-xs"
                            >
                                <RefreshCw className="h-3 w-3" />
                                <span>Regenerate</span>
                            </Button>
                        </div>
                    </div>
                </Collapsible>
            </div>
        );
    }

    return null;
}

